version: "3"

services:

  db:
    image: postgres
    container_name: dbead
    environment:
      - POSTGRES_DB=ead
      - POSTGRES_USER=ead
      - POSTGRES_PASSWORD=ead
    ports:
      - '5429:5432'
    expose:
      - "5432"
    networks:
      - backend
    restart: always

  redis:
    image: redis
    container_name: redisead
    ports:
      - "6378:6379"
    expose:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    restart: always
    command: redis-server

#  api:
#    container_name: api-ead
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - '9990:9999'
#    expose:
#      - "9999"
#    depends_on:
#      - db
#      - redis
#    networks:
#      - backend
#    restart: always
#    #command: sh -c "flask db init && flask db migrate && flask db upgrade"

  api:
    image: danilloabsilva/flask-api:1.2
    container_name: api-ead
    ports:
      - '9990:9999'
    expose:
      - "9999"
    depends_on:
      - db
      - redis
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: "bridge"